version: '3.7'

services:
    mail:
        image: tvial/docker-mailserver:latest
        hostname: docker
        domainname: docker.cloudyhost.net
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - mail_data:/var/mail
            - mail_state:/var/mail-state
            - mail_config:/tmp/docker-mailserver
            - /etc/letsencrypt/live/cloudyhost.net:/etc/letsencrypt:ro
            - /etc/localtime:/etc/localtime:ro

    webmail:
        image: roundcube/roundcubemail
        environment:
            - ROUNDCUBEMAIL_DEFAULT_HOST=mail
            - ROUNDCUBEMAIL_SMTP_SERVER=mail
        depends_on:
            - mail
            - webmail_db
        ports:
            - "${WEBMAIL_PORT}:80"
        volumes:
            - webmail_db:/var/lib/mysql

    webmail_db:
        image: mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAMING}
            - MYSQL_USER=${DATABASE_NAMING}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            

volumes:
    mail_data:
    mail_state:
    mail_config:
    webmail_db: