version: '3.7'

services:
    mail:
        image: tvial/docker-mailserver:latest
        hostname: docker
        domainname: docker.cloudyhost.net
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - maildata:/var/mail
            - mailstate:/var/mail-state
            - mailconfig:/tmp/docker-mailserver/
            - /etc/letsencrypt/live/cloudyhost.net:/etc/letsencrypt/:ro
            - /etc/localtime:/etc/localtime:ro

    webmail:
        image: roundcube/roundcubemail
        environment:
            - ROUNDCUBEMAIL_DEFAULT_HOST=mail
            - ROUNDCUBEMAIL_SMTP_SERVER=mail
        ports:
            - "${WEBMAIL_PORT}:80"

volumes:
    maildata:
    mailstate:
    mailconfig: